machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
  node:
    version: 8.2.0
dependencies:
  override:
    - npm install
  cache_directories:
    - "node_modules"
    - ~/.yarn
    - ~/.cache/yarn
